### ISSUE TITLE
Demo on Readme is wrong

### ISSUE THREAD

**Issue by fpw23** [Eightyplus/react-json-editor#1]
I tried copying the demo code on the ReadMe and ran into an error.  In the callback the changes variable does not have a json property, instead the changes variable is the changed json.

```
callback = (changes) => {
    this.setState({json: **changes.json**});
  };
```

I changed it to this and it works

```
callback = (changes) => {
    this.setState({json: **changes**});
  };
```

**Comment by Eightyplus** [comment]
You are right. I forgot to update the Readme after a refactor. Thanks
