### ISSUE TITLE
How can I rollback changes?

### ISSUE THREAD

**Issue by kilik52** [Eightyplus/react-json-editor#2]
I've got a default state for the json. After editing, I want to let the users rollback their changes to the default json. How can I do that?

**Comment by Eightyplus** [comment]
guess you need a function to handle the rollback

```JavaScript
rollback = () => {
     this.setState({json: defaultJson});
}
```

**Comment by kilik52** [comment]
are u sure this works?   Because i've tried   

````
this.setState({json: defaultJson});
````

But the value in JSON Editor did not change.   How to force JSON Editor to reload?
My guess is that JSON Editor keep trace of its own state,  it will not change with the component's state.

**Comment by Eightyplus** [comment]
Sorry for the late reply, I'm having the flu.

I just tested the code and it works by this example.
```JavaScript
  reset = () => {
    let defaultJson = {"myarray": ["bla", "bla", "bla"]}
    this.setState({json: defaultJson})
  };
```

I see some errors in the console. Maybe there is a dependency error? I solved mine by following http://stackoverflow.com/a/37896786/626741 
When I get better I should update this package.

If you would like more help, then please post some more code. 👍

**Comment by kilik52** [comment]
Thank you for your reply. I'm gonna try again. Wish you will recover soon

**Comment by kilik52** [comment]
It Works. Sorry for the false alarm

**Comment by Eightyplus** [comment]
Super :)
